### ISSUE TITLE
Refactoring needed for use cases package

### ISSUE THREAD

**Issue by andrewcoool** [CSC207-UofT/course-project-puppy-eyes#29]
This issue applies to any other folder you find that's way too long. We should probably separate any package with too many classes into subpackages.

For instance, what we're doing on front end is:
use_cases/request_models
use_cases/response_models
...
and the actual use case classes just go under use_cases.

If you find a better way, feel free to do that instead but let me know so I can update that on front-end to keep things consistent

**Comment by kennethtran77** [comment]
Moved each use case into its own folder, resolved as of feature/implement-images
