### ISSUE TITLE
Discrepancy between API docs and behaviour

### ISSUE THREAD

**Issue by andrewcoool** [CSC207-UofT/course-project-puppy-eyes#36]
Get Potential Matches returns its list of pet data with key potentialmatches instead of petIds as it is in docs.

![ShareX_2021-12-04_23-17-39](https://user-images.githubusercontent.com/35282796/144733317-a3745ea5-dd15-4d50-ae16-d07eb0b56a38.png)

**Comment by kennethtran77** [comment]
Fixed as of latest feature/refactor
