### ISSUE TITLE
Unmatch endpoint broken

### ISSUE THREAD

**Issue by andrewcoool** [CSC207-UofT/course-project-puppy-eyes#40]
The unmatch pets endpoint has unexpected behaviour. 

As an example, browse the database and see that there is a match relation between pets 10 and 12. 
The pets also return each other with the getMatches endpoint.

Doing an unmatch both from cmdline and through web with petId1=10 and petId2=12 fails and it says that the pets are not matched.

**Comment by kennethtran77** [comment]
Resolved in feature/refactor
